### ISSUE TITLE
Erreur au lancement

### ISSUE THREAD

**Issue by chabchab** [essembeh/kimsufi-checker#1]
Merci pour le partage, malheureusement le script ne se lance pas...
J'ai pourtant installé toutes les dépendances via pip install et dnf install (sous fedora).
Voici l'erreur : une idée ? 

$ kimsufi-checker
Traceback (most recent call last):
  File "/home/benoit/.local/bin/kimsufi-checker", line 11, in <module>
    load_entry_point('kimsufichecker==1.0.post2+g4ad41b7', 'console_scripts', 'kimsufi-checker')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/benoit/.local/lib/python2.7/site-packages/kimsufichecker/__main__.py", line 20
    def execute(command: str, plan: str):
                       ^
SyntaxError: invalid syntax

**Comment by essembeh** [comment]
Salut

Je viens de tester depuis un container Docker basé sur fedora:latest, et je tiens à préciser que je ne connais pas du tout les distribs Fedora :)

J'ai commencé par un 
$ dnf update
$ dnf install git
$ pip3 install git+https://github.com/essembeh/kimsufi-checker

Je me suis apercu que j'avais oublié la dépendance sur la lib *requests* dans le setup.py.
Une fois ce problème corrigé, ca marche pour moi sous fedora.

Mais le message d'erreur que j'ai eu n'était pas le même que le tien.
Pour ton problème je pense juste que c'est parce que tu utilises *pip* et pas *pip3*, j'ai mis à jour la doc aussi pour ca.

**Comment by chabchab** [comment]
effectivement c'était du à l'utilisation de pip et non de pip3 !
Merci pour cette réponse rapide... et je n'ai plus qu'à attendre ma dispo kimsufi ;)
